export const variantsTableMockData = [
  {
    id: '1',
    name: 'Variant Job 1',
    startTime: '01:00',
    endTime: '02:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '2',
    name: 'Variant Job 2',
    startTime: '03:00',
    endTime: '04:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '3',
    name: 'Variant Job 3',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '4',
    name: 'Variant Job 4',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '5',
    name: 'Variant Job 5',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '6',
    name: 'Variant Job 6',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '7',
    name: 'Variant Job 7',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '8',
    name: 'Variant Job 8',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '9',
    name: 'Variant Job 9',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '10',
    name: 'Variant Job 10',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '11',
    name: 'Variant Job 11',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
];

export const productsTableMockData = [
  {
    id: '1',
    name: 'Job 1',
    startTime: '01:00',
    endTime: '02:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '2',
    name: 'Job 2',
    startTime: '03:00',
    endTime: '04:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '3',
    name: 'Job 3',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Success',
    viewPayload: 'None',
  },
  {
    id: '4',
    name: 'Job 4',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '5',
    name: 'Job 5',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '6',
    name: 'Job 6',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '7',
    name: 'Job 7',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '8',
    name: 'Job 8',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '9',
    name: 'Job 9',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '10',
    name: 'Job 10',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
  {
    id: '11',
    name: 'Job 11',
    startTime: '05:00',
    endTime: '06:00',
    status: 'Failed',
    viewPayload: 'None',
  },
];
